In [1]:
import pandas as pd
import os

In [2]:
hostname = os.uname().nodename
if hostname == "Aarons-M3-Pro-MacBook-Pro":
    folder_path = "/Users/aarongzy/Programming/Penn/class/CIS5500/project/CIS5500_Project/data"
    cleaned_folder_path = "/Users/aarongzy/Programming/Penn/class/CIS5500/project/CIS5500_Project/cleaned_data"

In [3]:
# read in tables as pandas dfs
imdb_movies_rev_file = os.path.join(folder_path, "imdb_movies.csv")
streaming_platform_file = os.path.join(folder_path, "streaming_platform.csv")
name_basics_file = os.path.join(folder_path, "name.basics.tsv")
title_basics_file = os.path.join(folder_path, "title.basics.tsv")
title_ratings_file = os.path.join(folder_path, "title.ratings.tsv")

imdb_movies_rev = pd.read_csv(imdb_movies_rev_file)
streaming_platform = pd.read_csv(streaming_platform_file)
name_basics = pd.read_csv(name_basics_file, sep='\t')
title_basics = pd.read_csv(title_basics_file, sep='\t')
title_ratings = pd.read_csv(title_ratings_file, sep='\t')

/var/folders/lv/krd0s0rn0_j8tb5gd4m0k7000000gn/T/ipykernel_20235/1933208725.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  title_basics = pd.read_csv(title_basics_file, sep='\t')

In [4]:
# # print out the column names
# print("Cost and revenue: \n", imdb_movies_rev.columns)
# print("--------")
# print("Streaming platform: \n", streaming_platform.columns)
# print("--------")
# print("IMDb Personnel: \n", name_basics.columns)
# print("--------")
# print("IMDb Movie: \n", title_basics.columns)
# print("--------")
# print("IMDb Ratings: \n", title_ratings.columns)

In [5]:
# Part 1: Make all tables 1NF
# imdb_movies_rev: need to atomize genre and crew
imdb_movies_rev = imdb_movies_rev.assign(genre=imdb_movies_rev["genre"].str.split(",")).explode("genre")
imdb_movies_rev = imdb_movies_rev.assign(crew=imdb_movies_rev["crew"].str.split(",")).explode("crew")
# imdb_movies_rev

In [6]:
# streaming_platform: need to atomize genres and production_countries
# remove square brackets from genres and production countries
streaming_platform["genres"] = streaming_platform["genres"].apply(lambda x: x.replace("[", "").replace("]", "").replace("'", ""))
streaming_platform["production_countries"] = streaming_platform["production_countries"].apply(lambda x: x.replace("[", "").replace("]", "").replace("'", ""))
streaming_platform = streaming_platform.assign(genres=streaming_platform["genres"].str.split(",")).explode("genres")
streaming_platform = streaming_platform.assign(production_countries=streaming_platform["production_countries"].str.split(",")).explode("production_countries")
# streaming_platform

In [7]:
# name_basics: need to atomize primaryProfession, knownForTitles
name_basics = name_basics.assign(primaryProfession=name_basics["primaryProfession"].str.split(",")).explode("primaryProfession")
name_basics = name_basics.assign(knownForTitles=name_basics["knownForTitles"].str.split(",")).explode("knownForTitles")
# name_basics

In [8]:
# title_basics: need to atomize genres
title_basics = title_basics.assign(genres=title_basics["genres"].str.split(",")).explode("genres")
# Assuming title_basics is your DataFrame
title_basics.replace('\\N', None, inplace=True)
title_basics

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,None,1,Documentary
0,tt0000001,short,Carmencita,Carmencita,0,1894,None,1,Short
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,None,5,Animation
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,None,5,Short
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,None,4,Animation
...,...,...,...,...,...,...,...,...,...
10590865,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,None,None,Family
10590866,tt9916856,short,The Wind,The Wind,0,2015,None,27,Short
10590867,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,None,10,Adventure
10590867,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,None,10,Animation
10590867,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,None,10,Comedy

In [9]:
# Part 2: Only retain necessary columns
# print out the column names
print("Cost and revenue (imdb_movies_rev): \n", imdb_movies_rev.columns)
print("--------")
print("Streaming platform (streaming_platform): \n", streaming_platform.columns)
print("--------")
print("IMDb Personnel (name_basics): \n", name_basics.columns)
print("--------")
print("IMDb Movie (title_basics): \n", title_basics.columns)
print("--------")
print("IMDb Ratings (title_ratings): \n", title_ratings.columns)

Cost and revenue (imdb_movies_rev):
 Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='object')
--------
Streaming platform (streaming_platform):
 Index(['Unnamed: 0', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'imdb_id', 'imdb_score', 'imdb_votes', 'platform'],
      dtype='object')
--------
IMDb Personnel (name_basics):
 Index(['nconst', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession',
       'knownForTitles'],
      dtype='object')
--------
IMDb Movie (title_basics):
 Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres'],
      dtype='object')
--------
IMDb Ratings (title_ratings):
 Index(['tconst', 'averageRating', 'numVotes'], dtype='object')

In [10]:
# name_basics: delete birthYear, deathYear
print(name_basics.columns)
print("Deleting birthYear, deathYear")
name_basics_reduced = name_basics.drop(columns=["birthYear", "deathYear"])
print(name_basics_reduced.columns)

Index(['nconst', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession',
       'knownForTitles'],
      dtype='object')
Deleting birthYear, deathYear
Index(['nconst', 'primaryName', 'primaryProfession', 'knownForTitles'], dtype='object')

In [11]:
# imdb_movies_rev: delete genre, crew, orig_lang
print(imdb_movies_rev.columns)
print("Deleting genre, crew, orig_lang")
imdb_movies_rev_reduced = imdb_movies_rev.drop(columns=["genre","crew","orig_lang"])
print(imdb_movies_rev_reduced.columns)

Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='object')
Deleting genre, crew, orig_lang
Index(['names', 'date_x', 'score', 'overview', 'orig_title', 'status',
       'budget_x', 'revenue', 'country'],
      dtype='object')

In [12]:
# streaming_platform: delete release_year, runtime, genres, imdb_score, imdb_votes
print(streaming_platform.columns)
print("Deleting release_year, runtime, genres, imdb_score, imdb_votes")
streaming_platform_reduced = streaming_platform.drop(columns=["release_year", "runtime", "genres", "imdb_score", "imdb_votes"])
print(streaming_platform_reduced.columns)

Index(['Unnamed: 0', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'imdb_id', 'imdb_score', 'imdb_votes', 'platform'],
      dtype='object')
Deleting release_year, runtime, genres, imdb_score, imdb_votes
Index(['Unnamed: 0', 'title', 'type', 'description', 'age_certification',
       'production_countries', 'imdb_id', 'platform'],
      dtype='object')

In [13]:
########## Additional data cleanups

# Convert 'date_x' column to datetime format, handling empty strings
imdb_movies_rev_reduced['date_x'] = pd.to_datetime(imdb_movies_rev_reduced['date_x'], format='%m/%d/%Y', errors='coerce')
# Format 'date_x' column to 'YYYY-MM-DD' format, ignoring NaT values
imdb_movies_rev_reduced['date_x'] = imdb_movies_rev_reduced['date_x'].dt.strftime('%Y-%m-%d')

# remove duplicate keys in title_basics
title_basics.drop_duplicates(subset=['tconst'], keep='first', inplace=True)

# add indices and use that as primary key in name_basics
name_basics_reduced['id'] = range(1, len(name_basics_reduced) + 1)
# To move the 'Index' column to the leftmost position:
cols = name_basics_reduced.columns.tolist()
cols = ['id'] + [col for col in cols if col != 'id']
name_basics_reduced = name_basics_reduced[cols]

# add indices and use that as primary key in streaming_platform_reduced
streaming_platform_reduced['id'] = range(1, len(streaming_platform_reduced) + 1)
# To move the 'Index' column to the leftmost position:
cols = streaming_platform_reduced.columns.tolist()
cols = ['id'] + [col for col in cols if col != 'id']
streaming_platform_reduced = streaming_platform_reduced[cols]

# strip preceding space in imdb_movies_rev["status"]
imdb_movies_rev_reduced["status"] = imdb_movies_rev_reduced["status"].str.strip()

# drop duplicates in imdb_moimdb_movies_rev_reduced (names is the primary key)
imdb_movies_rev_reduced.drop_duplicates(subset="names", keep="first", inplace=True)

In [14]:
# exported cleaned data
name_basics_reduced.to_csv(os.path.join(cleaned_folder_path, "name_basics.csv"))
title_basics.to_csv(os.path.join(cleaned_folder_path, "title_basics.csv"))
title_ratings.to_csv(os.path.join(cleaned_folder_path, "title_ratings.csv"))
imdb_movies_rev_reduced.to_csv(os.path.join(cleaned_folder_path, "imdb_movies_rev.csv"))
streaming_platform_reduced.to_csv(os.path.join(cleaned_folder_path, "streaming_platform.csv"))

In [15]:
name_basics_reduced

,id,nconst,primaryName,primaryProfession,knownForTitles
0,1,nm0000001,Fred Astaire,soundtrack,tt0027125
0,2,nm0000001,Fred Astaire,soundtrack,tt0050419
0,3,nm0000001,Fred Astaire,soundtrack,tt0053137
0,4,nm0000001,Fred Astaire,soundtrack,tt0072308
0,5,nm0000001,Fred Astaire,actor,tt0027125
...,...,...,...,...,...
13299461,35701079,nm9993714,Romeo del Rosario,art_department,tt11657662
13299462,35701080,nm9993716,Essias Loberg,NaN,\N
13299463,35701081,nm9993717,Harikrishnan Rajan,cinematographer,tt8736744
13299464,35701082,nm9993718,Aayush Nair,cinematographer,tt8736744
13299465,35701083,nm9993719,Andre Hill,NaN,\N

In [16]:
# output files with the first 1000 rows only
name_basics_reduced.head(100).to_csv(os.path.join(cleaned_folder_path, "name_basics_reduced_100.csv"), index=False)
imdb_movies_rev_reduced.head(100).to_csv(os.path.join(cleaned_folder_path, "imdb_movies_rev_reduced_100.csv"), index=False)
streaming_platform_reduced.head(100).to_csv(os.path.join(cleaned_folder_path, "streaming_platform_reduced_100.csv"), index=False)
title_basics.head(100).to_csv(os.path.join(cleaned_folder_path, "title_basics_100.csv"), index=False)
title_ratings.head(100).to_csv(os.path.join(cleaned_folder_path, "title_ratings_100.csv"), index=False)